ms:
  keycloak:
    serverUrl: http://localhost:8080/
    realm: simesrealm
    clientId: users-admin
    clientSecret: 2NAcS9be3EvJsUd8a6L2hcpe7s7vSCY7

spring:
  application:
    name: ms-users
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/simesrealm
      client:
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            client-id: users-admin
            client-secret: 2NAcS9be3EvJsUd8a6L2hcpe7s7vSCY7
            token-uri: http://localhost:8080/realms/simesrealm/protocol/openid-connect/token

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8081

