INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(), 'Jhon', 'courses/Java', 500);
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(), 'Michael', 'courses/Java', 500);
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(), 'Peter', 'courses/Java', 500);
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(), 'Sebastian', 'courses/Java', 500);
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(), 'Aaron', 'courses/Java', 500);
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(), 'William', 'courses/Java', 500);
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(), 'b4bc1311-b75b-48e1-8e94-0e418e7498fe', 'courses/Java', 1500);
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(), 'b4bc1311-b75b-48e1-8e94-0e418e7498fe', 'courses/Java', 1500);
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(), 'b4bc1311-b75b-48e1-8e94-0e418e7498fe', 'courses/Java', 1500);

